FROM postgres

RUN usermod -u 1000 postgres
# atribuir a permissões do conteudo do volume de dados de dentro do container
# para o usuario "postgres" que  é o usuario criado dentro de um container postegres.
#Pos padram o usuário 1000 no postegres seria o Node, então usamos esse recurso para dizer
# que o usupario 1 sera o postgres, com isso teremos permissão para acessar o volume criado

